# This file was generated by GoReleaser. DO NOT EDIT.
cask "odc" do
  version "0.1.0-rc24"

  on_macos do
    on_intel do
      url "https://github.com/michaeldcanady/go-onedrive/releases/download/v#{version}/odc_Darwin_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "9ac3489e98dced1274e12098012f8c56004173895d36fc5d04afc96f24081122"
    end
    on_arm do
      url "https://github.com/michaeldcanady/go-onedrive/releases/download/v#{version}/odc_Darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "2e044c949efa4d36db51cc1cab913ff12e4fc28f7ed6eaf9138a62a1d43aadf6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/michaeldcanady/go-onedrive/releases/download/v#{version}/odc_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "25acbce0c6ac19468e32d430424e46b9d8bb340bce330f5aa5f84a1974ec1581"
    end
    on_arm do
      url "https://github.com/michaeldcanady/go-onedrive/releases/download/v#{version}/odc_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "489be0546d685111b0bd816bfc79e1d34a69c6b1a847193909584af530ab34a4"
    end
  end

  name "odc"
  desc "odc is a CLI tool designed to interact with OneDrive as a Unix-style file system."
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "odc"
  bash_completion "completions/odc.bash"
  fish_completion "completions/odc.fish"
  zsh_completion "completions/odc.zsh"
  generate_completions_from_executable "odc", "completions",
    base_name: "odc",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required

end
