# This file was generated by GoReleaser. DO NOT EDIT.
cask "odc" do
  version "0.1.0-rc22"

  on_linux do
    on_intel do
      url "https://github.com/michaeldcanady/go-onedrive/releases/download/v#{version}/odc_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "f1b4480a2405b10c0e2251e219fadad360a435beee516be2e451fbed965a212e"
    end
    on_arm do
      url "https://github.com/michaeldcanady/go-onedrive/releases/download/v#{version}/odc_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "03166ddb7f53e5e1869778d32c152a89f7b6bbc64db189ced226b627190980dd"
    end
  end

  name "odc"
  desc "odc is a CLI tool designed to interact with OneDrive as a Unix-style file system."
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "odc"
  bash_completion "completions/odc.bash"
  fish_completion "completions/odc.fish"
  zsh_completion "completions/odc.zsh"
  generate_completions_from_executable "odc", "completions",
    base_name: "odc",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required

end
