# This file was generated by GoReleaser. DO NOT EDIT.
cask "odc" do
  version "0.1.0-rc23"

  on_linux do
    on_intel do
      url "https://github.com/michaeldcanady/go-onedrive/releases/download/v#{version}/odc_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "56b70dd9f63ed4036f3af29e4bc76c1d8ae72304ecb85fd426011f1dae88a37b"
    end
    on_arm do
      url "https://github.com/michaeldcanady/go-onedrive/releases/download/v#{version}/odc_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "ea83970e6976a23e23df985cac6d99d7252975a7301b6379fbf643ae6a4fbfb4"
    end
  end

  name "odc"
  desc "odc is a CLI tool designed to interact with OneDrive as a Unix-style file system."
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "odc"
  bash_completion "completions/odc.bash"
  fish_completion "completions/odc.fish"
  zsh_completion "completions/odc.zsh"
  generate_completions_from_executable "odc", "completions",
    base_name: "odc",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required

end
